config/routes.rb
Locafe::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  devise_for :admins

  resources :locations
  resources :users

  root :to => 'locations#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :registerable, :confirmable, :lockable, :timeoutable and :omniauthable, :recoverable,
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/location.rb
class Location < ActiveRecord::Base
	validates_uniqueness_of :address, :message => "Already Exists"
	extend FriendlyId
		friendly_id :name, :use => :slugged

	geocoded_by :full_address
	attr_accessible :name, :address, :city, :state, :zip, :country, :phone, :url, :gluten, :dog, :wifi, :delivery, :latitude, :longitude
	
	belongs_to :user
	validates :user_id, :presence => true
	after_validation :geocode, :if => :address_changed?

	def full_address
		[address, city, state, zip, country].compact.join(', ')
	end
	
	default_scope :order => 'locations.created_at DESC'
	
end

app/models/user.rb
class User < ActiveRecord::Base
	extend FriendlyId
		friendly_id :username, :use => :slugged

	has_many :locations, :dependent => :destroy
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  validates_presence_of :username
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
 
  # GET /locations
  # GET /locations.json
  def index
      if params[:search].present?
        @locations = Location.near(params[:search], 50, :order => :distance).paginate(:per_page => 10, :page => params[:page])
      else
        @locations = Location.order('created_at desc').paginate(:per_page => 10, :page => params[:page])
      end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json

  def create
    @location  = current_user.locations.build(params[:location])
    if @location.save
      flash[:success] = "Local.ja created!"
      redirect_to root_path
    else
      render 'users/index'
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	def create
		if verify_recaptcha
			super
		else
			build_resource
			clean_up_passwords(resource)
			flash[:alert] = "Error in the reCaptcha code. Please try again"
			render_with_scope :new
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
		@location = @user.locations.paginate(:page => params[:page])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def title(page_title)
		content_for(:title) { page_title }
	end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_header.html.erb
<div class="row">
	<div class="eight columns">
		<h1><%= link_to image_tag("logo3.png" ), root_path %></h1>
	</div>
	<div class="four columns">
			<p class="nav">
			<% if admin_signed_in? %>
				YOU ARE IN GOD MODE <%= current_admin.email %>
				<%= link_to "Return to Mortality", destroy_admin_session_path, :method => :delete %> |||
			<% end %>
			<% if user_signed_in? %>
			    signed in as <strong><%= current_user.username %></strong> | <%= link_to "Profile", current_user %> | <%= link_to "Account", edit_user_registration_path %> | <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
			  <% else %>
			    <%= link_to "sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
			  <% end %>
			  </p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffee.local.jam <%= yield :title %></title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
	<div class="container">
		<div class="header">
			<div class="row">
				<%= render 'layouts/header' %>
			</div>
		</div>
		<div class="content">
			<div class="row">
			<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>

app/views/locations/_form.html.erb
<%= simple_form_for @location do |f| %>

<%= f.input :name, :required => true %>
<%= f.input :address, :required => true %>
<%= f.input :city, :required => true %>
<%= f.input :state, :required => true %>
<%= f.input :zip %>
<%= f.input :country %>
<%= f.input :phone %>
<%= f.input :url %>
<%= f.input :gluten, :label => "Gluten Free Options?" %>
<%= f.input :dog, :label => "Pet Friendly Areas?" %>
<%= f.input :wifi, :label => "WiFi Internet Access?" %>
<%= f.input :delivery, :label => "Delivery Option?" %>
<%= f.button :submit, :class => "button nice white" %>
<% end %>

app/views/locations/_location.html.erb
<% @location.each do |location| %>
<p>
<h6><%= link_to location.name, location %>,&nbsp;<%= location.city %></h6><br />
Posted <%= time_ago_in_words(location.created_at) %> ago.
<hr />
</p>
<% end %>

app/views/locations/edit.html.erb
<h1>Edit Jam</h1>

<%= render 'form' %>

<%= link_to 'Show', @location, :class => "button nice white" %>
<%= link_to 'Back', locations_path, :class => "button nice white" %>

app/views/locations/index.html.erb
<% if current_user.nil? %>
<div class="row">
	<div class="four columns">
		<h5 style="padding-top:15px;">Welcome to Coffee.local.jam</h5>
		<blockquote>Bringing rewards for jamming locally. Studying? Business? Chilling? Resting? You name it, jam it and be rewarded.</blockquote>
		<p>Get in on the rewards, it's free and is all about coffee.
			<br />
			<div><%= link_to "sign up", new_user_registration_path, :class => "button nice white" %></div>
		</p>
	</div>
	<div class="eight columns">
		<%= image_tag('http://coffeelocal.s3.amazonaws.com/coffeelocaljam-diagram.png') %>
	</div>
</div>
<hr />
<% end %>
<div class="row">
<div class="twelve columns">
<h1>search coffee.jams near you</h1>
<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil, :class => "button nice white" %>
  </p>
<% end %>
<hr />
<% @locations.each do |location| %>
<div class="row">
<p><h4><%= link_to location.name, location %> <%= location.city %> <%= location.state if location.state.present? %>
    <%= image_tag("glutenfree.png", :alt => "Gluten Free Options", :title => "Gluten Free Options", :style => "height:28px;") if location.gluten.present? %>
    <%= image_tag("petfriendly.png", :alt => "Pet Friendly Area", :title => "Pet Friendly Areas", :style => "height:28px;") if location.dog.present? %>
    <%= image_tag("wifi.png", :alt => "Wifi Available", :title => "Wifi Available", :style => "height:28px;") if location.wifi.present? %>
    <%= image_tag("delivery.png", :alt => "Delivery Option", :title => "Delivery Option", :style => "height:28px;") if location.delivery.present? %>
</h4>
    
<%= link_to 'Destroy', location, confirm: 'Are you sure?', method: :delete if admin_signed_in? %>
</p>
</div>
<% end %>
<hr />
<%= will_paginate @location %>

<%= link_to 'New Location', new_location_path, :class => "button nice white" if user_signed_in? %>
<%= link_to 'New Location', new_location_path, :class => "button nice white" if admin_signed_in? %>
</div>
</div>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path, :class => "button nice white" %>

app/views/locations/show.html.erb
<% title "#{@location.name} #{@location.city}" %>
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="six columns">
    <p>
      <h1><%= @location.name %></h1>
    </p>
    <p>
      <%= image_tag("glutenfree.png", :alt => "Gluten Free Options", :title => "Gluten Free Options") if @location.gluten.present? %>
      <%= image_tag("petfriendly.png", :alt => "Pet Friendly Area", :title => "Pet Friendly Areas") if @location.dog.present? %>
      <%= image_tag("wifi.png", :alt => "Wifi Available", :title => "Wifi Available") if @location.wifi.present? %>
      <%= image_tag("delivery.png", :alt => "Delivery Option", :title => "Delivery Option") if @location.delivery.present? %>
    </p>
    <p>
      <strong><%= @location.address %>,
      <%= @location.city %>,
      <%= @location.state %>,
      <%= @location.zip %></strong> - 
      <%= @location.country %>
    </p>
    <p>
      <h5><%= @location.phone %></h5>
    </p>

    <p>
       <%= @location.url %>
    </p>
  </div>
  <div class="six columns">
    <div class="row">
      <%= image_tag "http://maps.google.com/maps/api/staticmap?size=460x230&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>
    </div>
    <div class="row">
      <h3>Nearby locations</h3>
        <ul>
        <% for location in @location.nearbys(10) %>
          <li><%= link_to location.name, location %> (<%= location.distance.to_f.round(2) %> miles)</li>
        <% end %>
        </ul>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_location_path(@location), :class => "button nice white" if user_signed_in? %>
<%= link_to 'Edit', edit_location_path(@location), :class => "button nice white" if admin_signed_in? %>
<%= link_to 'Back', locations_path, :class => "button nice white" %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<% title "#{@user.username}" %>
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="four columns">
    <h1><%= @user.username %></h1>
	<p style="box-shadow:5px 5px 15px #e5e5e5; padding:5px; background:#e5e5e5;">
		<%= image_tag('coffeecup.png') %>&nbsp;<%= @user.locations.count %>&nbsp;Points
		<br />
		<%= image_tag('jams.png') %>&nbsp;<%= pluralize(@total_location, "Jams") %>
	</p>
  </div>
	<div class="eight columns">
		<p><%= link_to "Add local.jam", new_location_path, :class => "button nice white" %></p>
		<p><h5>added coffee.local.jams</h5></p>
		<hr />
		<p>
		<% unless @user.locations.empty? %>
		<%= render 'locations/location' %>
		<%= will_paginate @location %>
		<% end %>
		</p>
	</div>
</div>